 Process: com.example.abhishek.financetracker.expensemanager.neopark, PID: 10969
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.abhishek.financetracker.expensemanager.neopark/com.example.abhishek.financetracker.expensemanager.neopark.RegisterActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.abhishek.financetracker.expensemanager.neopark. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3546)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3718)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7912)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.abhishek.financetracker.expensemanager.neopark. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
                                                                                                    	at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@22.0.0:1)
                                                                                                    	at com.example.abhishek.financetracker.expensemanager.neopark.RegisterActivity.initVariable(RegisterActivity.java:160)
                                                                                                    	at com.example.abhishek.financetracker.expensemanager.neopark.RegisterActivity.onCreate(RegisterActivity.java:58)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8109)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8083)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1308)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3519)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3718) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:236) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7912) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011) 
2025-02-19 17:20:03.630 10969-10969 Process              